<?php

namespace Database\Seeders;

use App\Models\Solution;
use Illuminate\Database\Seeder;

class SolutionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $solutions = [
            [
                'name' => 'Sistema de Gestión de Inventario',
                'slug' => 'gestion-inventario',
                'short_description' => 'Control total de tu inventario en tiempo real',
                'description' => 'Sistema completo para gestionar tu inventario con seguimiento en tiempo real, alertas de stock bajo, gestión de proveedores y reportes detallados.',
                'icon' => 'Package',
                'category' => 'Inventario',
                'features' => [
                    'Control de stock en tiempo real',
                    'Alertas de stock mínimo',
                    'Gestión de múltiples almacenes',
                    'Códigos de barras y QR',
                    'Reportes de movimientos',
                    'Integración con ventas',
                ],
                'benefits' => [
                    'Reduce pérdidas por desabastecimiento',
                    'Optimiza el capital de trabajo',
                    'Mejora la rotación de inventario',
                    'Automatiza procesos manuales',
                ],
                'target_audience' => ['Retail', 'Distribuidores', 'Mayoristas', 'Manufactura'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Sistema de Punto de Venta (POS)',
                'slug' => 'punto-venta',
                'short_description' => 'Procesa ventas rápidamente con nuestro POS moderno',
                'description' => 'Sistema de punto de venta completo con interfaz intuitiva, múltiples métodos de pago, facturación electrónica y reportes de ventas en tiempo real.',
                'icon' => 'CreditCard',
                'category' => 'Ventas',
                'features' => [
                    'Interfaz táctil intuitiva',
                    'Múltiples métodos de pago',
                    'Facturación electrónica',
                    'Gestión de turnos y caja',
                    'Descuentos y promociones',
                    'Reportes de ventas',
                ],
                'benefits' => [
                    'Agiliza el proceso de venta',
                    'Reduce errores humanos',
                    'Mejora la experiencia del cliente',
                    'Control total de caja',
                ],
                'target_audience' => ['Retail', 'Restaurantes', 'Farmacias', 'Supermercados'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'CRM - Gestión de Clientes',
                'slug' => 'crm-clientes',
                'short_description' => 'Administra y fideliza a tus clientes',
                'description' => 'Sistema CRM completo para gestionar relaciones con clientes, seguimiento de oportunidades, historial de interacciones y automatización de marketing.',
                'icon' => 'Users',
                'category' => 'Ventas',
                'features' => [
                    'Base de datos de clientes',
                    'Historial de interacciones',
                    'Seguimiento de oportunidades',
                    'Automatización de emails',
                    'Segmentación de clientes',
                    'Reportes de conversión',
                ],
                'benefits' => [
                    'Aumenta la retención de clientes',
                    'Mejora las tasas de conversión',
                    'Personaliza la comunicación',
                    'Identifica oportunidades de venta',
                ],
                'target_audience' => ['Servicios', 'B2B', 'Retail', 'Inmobiliarias'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'Sistema de Facturación Electrónica',
                'slug' => 'facturacion-electronica',
                'short_description' => 'Factura electrónicamente cumpliendo con la DGII',
                'description' => 'Sistema de facturación electrónica certificado por DGII con generación automática de NCF, envío por email y almacenamiento seguro.',
                'icon' => 'FileText',
                'category' => 'Contabilidad',
                'features' => [
                    'Generación automática de NCF',
                    'Facturación electrónica DGII',
                    'Envío automático por email',
                    'Plantillas personalizables',
                    'Notas de crédito',
                    'Reportes fiscales',
                ],
                'benefits' => [
                    'Cumplimiento fiscal garantizado',
                    'Reduce tiempo de facturación',
                    'Elimina errores manuales',
                    'Acceso desde cualquier lugar',
                ],
                'target_audience' => ['Todas las empresas', 'Autónomos', 'PYMES'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'Sistema de Recursos Humanos',
                'slug' => 'recursos-humanos',
                'short_description' => 'Gestiona tu equipo de forma eficiente',
                'description' => 'Sistema completo de RRHH con gestión de empleados, nómina, asistencia, vacaciones y evaluaciones de desempeño.',
                'icon' => 'UserCheck',
                'category' => 'RRHH',
                'features' => [
                    'Gestión de empleados',
                    'Control de asistencia',
                    'Cálculo de nómina',
                    'Gestión de vacaciones',
                    'Evaluaciones de desempeño',
                    'Documentos digitales',
                ],
                'benefits' => [
                    'Automatiza procesos de RRHH',
                    'Reduce errores en nómina',
                    'Mejora la comunicación interna',
                    'Centraliza información de empleados',
                ],
                'target_audience' => ['PYMES', 'Empresas medianas', 'Corporativos'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'Sistema de Contabilidad',
                'slug' => 'contabilidad',
                'short_description' => 'Lleva tu contabilidad de forma profesional',
                'description' => 'Sistema contable completo con plan de cuentas, libro diario, mayor, balance general y estados financieros.',
                'icon' => 'Calculator',
                'category' => 'Contabilidad',
                'features' => [
                    'Plan de cuentas personalizable',
                    'Libro diario y mayor',
                    'Balance general',
                    'Estado de resultados',
                    'Flujo de efectivo',
                    'Reportes fiscales',
                ],
                'benefits' => [
                    'Cumplimiento contable garantizado',
                    'Visibilidad financiera en tiempo real',
                    'Facilita auditorías',
                    'Reduce costos contables',
                ],
                'target_audience' => ['PYMES', 'Contadores', 'Empresas medianas'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'Sistema de Órdenes de Servicio',
                'slug' => 'ordenes-servicio',
                'short_description' => 'Gestiona servicios técnicos eficientemente',
                'description' => 'Sistema para gestionar órdenes de servicio técnico con asignación de técnicos, seguimiento en tiempo real y facturación integrada.',
                'icon' => 'Wrench',
                'category' => 'Servicios',
                'features' => [
                    'Creación de órdenes',
                    'Asignación de técnicos',
                    'Seguimiento GPS',
                    'Gestión de repuestos',
                    'Facturación integrada',
                    'Historial de servicios',
                ],
                'benefits' => [
                    'Optimiza rutas de técnicos',
                    'Mejora tiempos de respuesta',
                    'Aumenta satisfacción del cliente',
                    'Control total de servicios',
                ],
                'target_audience' => ['Servicios técnicos', 'Mantenimiento', 'Reparaciones'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'E-commerce',
                'slug' => 'ecommerce',
                'short_description' => 'Vende online con tu propia tienda',
                'description' => 'Plataforma de comercio electrónico completa con catálogo de productos, carrito de compras, pasarelas de pago y gestión de pedidos.',
                'icon' => 'ShoppingCart',
                'category' => 'Ventas',
                'features' => [
                    'Catálogo de productos',
                    'Carrito de compras',
                    'Múltiples pasarelas de pago',
                    'Gestión de pedidos',
                    'Envíos y logística',
                    'Marketing integrado',
                ],
                'benefits' => [
                    'Expande tu mercado 24/7',
                    'Reduce costos operativos',
                    'Aumenta ventas',
                    'Mejora experiencia del cliente',
                ],
                'target_audience' => ['Retail', 'Distribuidores', 'Marcas', 'Emprendedores'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 8,
            ],
            [
                'name' => 'Sistema de Reservas',
                'slug' => 'reservas',
                'short_description' => 'Gestiona reservas y citas fácilmente',
                'description' => 'Sistema de reservas online con calendario inteligente, confirmaciones automáticas y recordatorios por email/SMS.',
                'icon' => 'Calendar',
                'category' => 'Servicios',
                'features' => [
                    'Calendario de disponibilidad',
                    'Reservas online 24/7',
                    'Confirmaciones automáticas',
                    'Recordatorios SMS/Email',
                    'Gestión de recursos',
                    'Reportes de ocupación',
                ],
                'benefits' => [
                    'Reduce no-shows',
                    'Optimiza ocupación',
                    'Mejora experiencia del cliente',
                    'Ahorra tiempo administrativo',
                ],
                'target_audience' => ['Restaurantes', 'Salones', 'Consultorios', 'Hoteles'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 9,
            ],
            [
                'name' => 'Sistema de Delivery',
                'slug' => 'delivery',
                'short_description' => 'Optimiza tus entregas a domicilio',
                'description' => 'Sistema de gestión de entregas con asignación inteligente de repartidores, seguimiento GPS en tiempo real y confirmación de entrega.',
                'icon' => 'Truck',
                'category' => 'Logística',
                'features' => [
                    'Asignación automática',
                    'Seguimiento GPS',
                    'Optimización de rutas',
                    'Confirmación con QR',
                    'Notificaciones en tiempo real',
                    'Reportes de entregas',
                ],
                'benefits' => [
                    'Reduce tiempos de entrega',
                    'Optimiza costos de logística',
                    'Mejora satisfacción del cliente',
                    'Control total de entregas',
                ],
                'target_audience' => ['Restaurantes', 'Farmacias', 'Supermercados', 'E-commerce'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 10,
            ],
            [
                'name' => 'Sistema de Restaurante',
                'slug' => 'restaurante',
                'short_description' => 'Gestiona tu restaurante completamente',
                'description' => 'Sistema integral para restaurantes con POS, gestión de mesas, comandas de cocina, inventario y delivery integrado.',
                'icon' => 'Utensils',
                'category' => 'Restaurantes',
                'features' => [
                    'POS especializado',
                    'Gestión de mesas',
                    'Comandas digitales',
                    'Control de cocina',
                    'Inventario de ingredientes',
                    'Delivery integrado',
                ],
                'benefits' => [
                    'Agiliza el servicio',
                    'Reduce errores en pedidos',
                    'Optimiza inventario',
                    'Aumenta rotación de mesas',
                ],
                'target_audience' => ['Restaurantes', 'Cafeterías', 'Food trucks', 'Bares'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 11,
            ],
            [
                'name' => 'Sistema de Gimnasio',
                'slug' => 'gimnasio',
                'short_description' => 'Administra tu gimnasio eficientemente',
                'description' => 'Sistema completo para gimnasios con gestión de membresías, control de acceso, clases grupales y seguimiento de clientes.',
                'icon' => 'Dumbbell',
                'category' => 'Fitness',
                'features' => [
                    'Gestión de membresías',
                    'Control de acceso',
                    'Clases grupales',
                    'Rutinas personalizadas',
                    'Pagos recurrentes',
                    'App móvil para clientes',
                ],
                'benefits' => [
                    'Automatiza cobros',
                    'Mejora retención de clientes',
                    'Optimiza ocupación de clases',
                    'Reduce trabajo administrativo',
                ],
                'target_audience' => ['Gimnasios', 'Estudios', 'Centros deportivos'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 12,
            ],
            [
                'name' => 'Sistema de Educación',
                'slug' => 'educacion',
                'short_description' => 'Gestiona tu institución educativa',
                'description' => 'Sistema integral para instituciones educativas con gestión de estudiantes, calificaciones, asistencia y comunicación con padres.',
                'icon' => 'GraduationCap',
                'category' => 'Educación',
                'features' => [
                    'Gestión de estudiantes',
                    'Control de asistencia',
                    'Calificaciones y reportes',
                    'Portal de padres',
                    'Gestión de cursos',
                    'Facturación de colegiaturas',
                ],
                'benefits' => [
                    'Centraliza información académica',
                    'Mejora comunicación con padres',
                    'Automatiza procesos administrativos',
                    'Facilita seguimiento académico',
                ],
                'target_audience' => ['Colegios', 'Universidades', 'Academias', 'Institutos'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 13,
            ],
            [
                'name' => 'Sistema de Salud',
                'slug' => 'salud',
                'short_description' => 'Digitaliza tu consultorio o clínica',
                'description' => 'Sistema de gestión médica con expedientes electrónicos, citas, recetas digitales y facturación para consultorios y clínicas.',
                'icon' => 'Stethoscope',
                'category' => 'Salud',
                'features' => [
                    'Expedientes electrónicos',
                    'Gestión de citas',
                    'Recetas digitales',
                    'Historial médico',
                    'Facturación médica',
                    'Reportes clínicos',
                ],
                'benefits' => [
                    'Mejora atención al paciente',
                    'Cumplimiento normativo',
                    'Acceso rápido a historiales',
                    'Reduce errores médicos',
                ],
                'target_audience' => ['Consultorios', 'Clínicas', 'Hospitales', 'Laboratorios'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 14,
            ],
            [
                'name' => 'Sistema de Inmobiliaria',
                'slug' => 'inmobiliaria',
                'short_description' => 'Gestiona propiedades y ventas',
                'description' => 'Sistema para inmobiliarias con gestión de propiedades, clientes, visitas, contratos y comisiones de agentes.',
                'icon' => 'Building',
                'category' => 'Inmobiliaria',
                'features' => [
                    'Catálogo de propiedades',
                    'CRM de clientes',
                    'Gestión de visitas',
                    'Contratos digitales',
                    'Comisiones de agentes',
                    'Portal web integrado',
                ],
                'benefits' => [
                    'Aumenta visibilidad de propiedades',
                    'Mejora seguimiento de clientes',
                    'Automatiza procesos de venta',
                    'Control de comisiones',
                ],
                'target_audience' => ['Inmobiliarias', 'Agentes', 'Desarrolladores'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 15,
            ],
            [
                'name' => 'Sistema de Taller Mecánico',
                'slug' => 'taller-mecanico',
                'short_description' => 'Administra tu taller automotriz',
                'description' => 'Sistema especializado para talleres mecánicos con órdenes de trabajo, inventario de repuestos, historial de vehículos y facturación.',
                'icon' => 'Car',
                'category' => 'Automotriz',
                'features' => [
                    'Órdenes de trabajo',
                    'Historial de vehículos',
                    'Inventario de repuestos',
                    'Cotizaciones',
                    'Facturación integrada',
                    'Recordatorios de mantenimiento',
                ],
                'benefits' => [
                    'Mejora eficiencia del taller',
                    'Fideliza clientes',
                    'Control de inventario',
                    'Aumenta ventas de servicios',
                ],
                'target_audience' => ['Talleres', 'Concesionarios', 'Centros de servicio'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 16,
            ],
            [
                'name' => 'Sistema de Lavandería',
                'slug' => 'lavanderia',
                'short_description' => 'Gestiona tu lavandería profesionalmente',
                'description' => 'Sistema para lavanderías con control de prendas, tickets, entregas, precios por servicio y facturación.',
                'icon' => 'Shirt',
                'category' => 'Servicios',
                'features' => [
                    'Control de prendas',
                    'Tickets con código de barras',
                    'Gestión de entregas',
                    'Precios por servicio',
                    'Notificaciones automáticas',
                    'Facturación',
                ],
                'benefits' => [
                    'Reduce pérdida de prendas',
                    'Agiliza proceso de entrega',
                    'Mejora experiencia del cliente',
                    'Control de ingresos',
                ],
                'target_audience' => ['Lavanderías', 'Tintorerías', 'Hoteles'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 17,
            ],
            [
                'name' => 'Sistema de Farmacia',
                'slug' => 'farmacia',
                'short_description' => 'Gestiona tu farmacia integralmente',
                'description' => 'Sistema especializado para farmacias con control de medicamentos, vencimientos, recetas, ventas y reportes regulatorios.',
                'icon' => 'Pill',
                'category' => 'Salud',
                'features' => [
                    'Control de medicamentos',
                    'Alertas de vencimiento',
                    'Gestión de recetas',
                    'POS especializado',
                    'Control de lotes',
                    'Reportes regulatorios',
                ],
                'benefits' => [
                    'Cumplimiento regulatorio',
                    'Reduce pérdidas por vencimiento',
                    'Control de sustancias controladas',
                    'Optimiza inventario',
                ],
                'target_audience' => ['Farmacias', 'Droguerías', 'Distribuidores'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 30,
                'is_active' => true,
                'display_order' => 18,
            ],
            [
                'name' => 'Sistema de Hotel',
                'slug' => 'hotel',
                'short_description' => 'Administra tu hotel eficientemente',
                'description' => 'Sistema hotelero completo con reservas, check-in/out, housekeeping, POS, facturación y channel manager.',
                'icon' => 'Hotel',
                'category' => 'Hotelería',
                'features' => [
                    'Gestión de reservas',
                    'Check-in/out digital',
                    'Housekeeping',
                    'POS integrado',
                    'Channel manager',
                    'Facturación hotelera',
                ],
                'benefits' => [
                    'Maximiza ocupación',
                    'Mejora experiencia del huésped',
                    'Optimiza operaciones',
                    'Aumenta ingresos',
                ],
                'target_audience' => ['Hoteles', 'Hostales', 'Resorts', 'Apart-hoteles'],
                'pricing_model' => 'subscription',
                'demo_duration_minutes' => 45,
                'is_active' => true,
                'display_order' => 19,
            ],
        ];

        foreach ($solutions as $solution) {
            Solution::create($solution);
        }
    }
}
